### ISSUE TITLE
Missing plugin descriptor file

### ISSUE THREAD

**Issue by katebee** [snyk/teamcity-snyk-security-plugin#18]
Minor issue 😄 

Just added this plugin to TeamCity and the UI is reporting that there is no plugin descriptor file:

<img width="1304" alt="Screenshot 2019-07-24 at 11 40 18" src="https://user-images.githubusercontent.com/8607683/61787566-f4687000-ae07-11e9-8a39-2a172cee51f2.png">

This means that some information on the plugin is missing.

Row headings are:

Plugin name | Version | Vendor
------------ | ------- | --------

The information can be added by creating a `teamcity-plugin.xml` containing meta information about the plugin:

https://plugins.jetbrains.com/docs/teamcity/plugins-packaging.html

An example can be found here:

https://github.com/guardian/teamcity-s3-plugin/blob/master/teamcity-plugin.xml

Thanks Snyk team 👍

**Comment by yuliabaron** [comment]
Hi,

What version of TeamCity are you using?

**Comment by pavel-github** [comment]
hey-hey, @katebee. Did you downloaded plugin from JB portal or build it with `mvn package` itself? Because the descriptor exists and upload to JB portal would fail without descriptor :).

**Comment by pavel-github** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the `2018.2-7`.

Thank you!
